### ISSUE TITLE
Workflow does not run - SyntaxError: Unexpected token '?'

### ISSUE THREAD

**Issue by Schrolli91** [r0adkll/upload-google-play#203]
**Describe the bug**
Here is the Log output that I will get

```
/run/act/actions/r0adkll-***-google-play@v1/lib/index.js:2
/*! THIS FILE IS AUTO-GENERATED */const a=r(5[2]( ......
[ ... ]
SyntaxError: Unexpected token '?'
    at wrapSafe (internal/modules/cjs/loader.js:915:1[6](https://git.vps.####/####/###/actions/runs/187#jobstep-14-6))
    at Module._compile (internal/modules/cjs/loader.js:963:2[7](https://git.vps.####/###/###/actions/runs/187#jobstep-14-7))
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:[8](https://git.vps.###/###/###/actions/runs/187#jobstep-14-8)63:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:60:12)
    at internal/main/run_main_module.js:17:47
```

Any ideas what's wrong here? I'am running this on a self hosted runner via Gitea Action (mostly compatible to the github actions syntax - action runner is nektos/act)

**Comment by boswelja** [comment]
Which Node version are you running? I'm wondering if this is at all related to #208

**Comment by boswelja** [comment]
I assume updating to node20 fixed it, I will close this
