### ISSUE TITLE
System.ArgumentException: Unexpected type '' encountered while reading 'action manifest root'. The type 'MappingToken' was expected.

### ISSUE THREAD

**Issue by AChep** [r0adkll/upload-google-play#36]
Using the action as
```
      uses: r0adkll/upload-google-play@v1
      with:
        serviceAccountJsonPlainText: json
        packageName: com.example
        releaseFile: app/build/outputs/bundle/release/app-release.aab
        track: internal
```
I'm now getting the error
```
Error: r0adkll/upload-google-play/v1/action.yml:
Error: r0adkll/upload-google-play/v1/action.yml: (Line: 24, Col: 59, Idx: 971) - (Line: 24, Col: 111, Idx: 1023): While parsing a block mapping, did not find expected key.
Error: System.ArgumentException: Unexpected type '' encountered while reading 'action manifest root'. The type 'MappingToken' was expected.
   at GitHub.DistributedTask.ObjectTemplating.Tokens.TemplateTokenExtensions.AssertMapping(TemplateToken value, String objectDescription)
   at GitHub.Runner.Worker.ActionManifestManager.Load(IExecutionContext executionContext, String manifestFile)
Error: Fail to load r0adkll/upload-google-play/v1/action.yml
```

**Comment by r0adkll** [comment]
Closed per #37
